name: a4s-molprot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - rdkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - biopython
  - nbformat
  - nbclient
  - jupyter_client
  - ipykernel
  - pytest
